In [2]:
target_pos = []
for i in range(-160, 160, 5):
    for j in range (-225, 45, 5):
        for k in range(-45, 225, 5):
            # convert the degree to radiant position
            i_rad = i * 3.141592653589793 / 180.0
            j_rad = j * 3.141592653589793 / 180.0
            k_rad = k * 3.141592653589793 / 180.0
            target_pos.append([i_rad, j_rad, k_rad])
    pass
print(len(target_pos))

186624


In [3]:
import numpy as np
import csv

In [4]:
randomized_pos = np.random.permutation(target_pos)

In [5]:
len(randomized_pos)
for i in range(100):
    print(randomized_pos[i])

[ 1.22173048  0.34906585 -0.61086524]
[-2.35619449 -3.66519143  2.26892803]
[ 2.35619449 -1.30899694  0.        ]
[ 0.87266463 -0.6981317  -0.26179939]
[-0.34906585 -3.83972435  3.40339204]
[-1.3962634   0.08726646  2.44346095]
[-2.61799388  0.          1.48352986]
[-0.78539816 -3.40339204  0.95993109]
[-0.95993109 -1.91986218 -0.34906585]
[ 2.53072742 -2.96705973  1.74532925]
[-1.13446401 -2.0943951  -0.17453293]
[-0.78539816 -2.35619449  1.48352986]
[ 1.13446401 -2.35619449 -0.78539816]
[ 0.43633231 -0.78539816  0.17453293]
[1.13446401 0.43633231 1.30899694]
[ 2.61799388 -1.04719755  2.35619449]
[-0.61086524 -0.61086524  3.31612558]
[ 0.17453293 -0.6981317   2.18166156]
[-0.78539816 -2.96705973 -0.61086524]
[ 1.83259571 -0.17453293  2.18166156]
[-1.83259571  0.34906585  3.4906585 ]
[ 1.57079633 -0.52359878  3.57792497]
[ 0.95993109 -2.96705973  2.61799388]
[ 2.18166156 -0.34906585  0.52359878]
[ 0.87266463 -0.52359878  2.96705973]
[ 2.26892803 -3.22885912 -0.26179939]
[ 1.65806279 -0

In [7]:
# save to csv
with open('target_positions.csv', mode='w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(['pos1', 'pos2', 'pos3'])
    for i in range(100):
        writer.writerow(randomized_pos[i])